### ISSUE TITLE
[BUG] demo-properties 无法读取对应的artifactId 及 version的值.

### ISSUE THREAD

**Issue by yizhao1998** [xkcoding/spring-boot-demo#108]
**请先看[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md?utm_source=hacpai.com)**，并尝试到 **[issue 列表](https://github.com/xkcoding/spring-boot-demo/issues)** 搜寻是否已经有人遇到过同样的问题。

----

### 描述问题

请尽量清晰精准地描述你碰到的问题。

```bash
日志内容
```

### 期待的结果

请尽量清晰精准地描述你所期待的结果。

### 截屏或录像

如果可能，请尽量附加截图或录像来描述你遇到的问题。

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by xkcoding** [comment]
#31 看看和这个 issue 问题是否一致

**Comment by yizhao1998** [comment]
是一致的，只是因为要提pr所以先开了issue
