### ISSUE TITLE
老哥，可以整一个SSO的项目

### ISSUE THREAD

**Issue by Janche** [xkcoding/spring-boot-demo#12]

**Comment by realoldroot** [comment]
o是什么:flushed:

**Comment by Janche** [comment]
> o是什么😳

单点登录(SingleSign-On)

**Comment by xkcoding** [comment]
OK ，我添加到TODO里，话说现在还有9个demo欠着你们呢

**Comment by fuliang686** [comment]
老哥，等着你的sso

**Comment by cqboyone** [comment]
老哥，等你的单点登录

**Comment by xkcoding** [comment]
你们真是群魔鬼，我中秋节加班给你们补上 :sob:

**Comment by Janche** [comment]
希望老哥能够实现单点退出，加油

**Comment by coolflameSLZ** [comment]
老哥求单点登陆！跪谢

**Comment by PL315** [comment]
老哥，同求单点登录

**Comment by haochen2011** [comment]
老哥人呢，sso   i  期待

**Comment by manluqiusuo0615** [comment]
我也在写，希望能从你哪里学习一下！先行谢过！

**Comment by wangwjt** [comment]
老哥 开发完了吗

**Comment by ChenXbFrank** [comment]
老哥，sso呢 等着呢  #苦笑#

**Comment by zlxhmn** [comment]
都这么着急呢，hh

**Comment by zlxhmn** [comment]
都这么着急呢，hh

**Comment by Janche** [comment]
这里有个类似的demo：https://github.com/Janche/sso-oauth2-server
https://github.com/Janche/sso-oauth2-client

**Comment by daidai21** [comment]
+1

**Comment by haochen2011** [comment]
不要回复我，我不是作者，我也是提问的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "."<notifications@github.com&gt;; 
发送时间: 2020年8月27日(星期四) 凌晨1:48
收件人: "xkcoding/spring-boot-demo"<spring-boot-demo@noreply.github.com&gt;; 
抄送: "boy is super"<1409631642@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [xkcoding/spring-boot-demo] 老哥，可以整一个SSO的项目 (#12)





 
+1

**Comment by woszzc** [comment]
开发完了么?


| |
woszzc
|
|
woszzc@163.com
|
签名由网易邮箱大师定制
在2020年8月27日 14:50，haochen2011<notifications@github.com> 写道：

不要回复我，我不是作者，我也是提问的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "."<notifications@github.com&gt;;
发送时间: 2020年8月27日(星期四) 凌晨1:48
收件人: "xkcoding/spring-boot-demo"<spring-boot-demo@noreply.github.com&gt;;
抄送: "boy is super"<1409631642@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;;
主题: Re: [xkcoding/spring-boot-demo] 老哥，可以整一个SSO的项目 (#12)






+1

**Comment by haochen2011** [comment]
和我有啥关系，我也是读者，你要问作者




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "woszzc"<notifications@github.com&gt;; 
发送时间: 2020年8月27日(星期四) 下午2:53
收件人: "xkcoding/spring-boot-demo"<spring-boot-demo@noreply.github.com&gt;; 
抄送: "boy is super"<1409631642@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [xkcoding/spring-boot-demo] 老哥，可以整一个SSO的项目 (#12)





 
 
 开发完了么?
 
 
 | |
 woszzc
 |
 |
 woszzc@163.com
 |
 签名由网易邮箱大师定制
 在2020年8月27日 14:50，haochen2011<notifications@github.com&gt; 写道：
 
 不要回复我，我不是作者，我也是提问的
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
 发件人: "."<notifications@github.com&amp;gt;;
 发送时间: 2020年8月27日(星期四) 凌晨1:48
 收件人: "xkcoding/spring-boot-demo"<spring-boot-demo@noreply.github.com&amp;gt;;
 抄送: "boy is super"<1409631642@qq.com&amp;gt;; "Comment"<comment@noreply.github.com&amp;gt;;
 主题: Re: [xkcoding/spring-boot-demo] 老哥，可以整一个SSO的项目 (#12)
 
 
 
 
 
 
 +1

**Comment by SuMiaoALi** [comment]
我可以写sso提交pr不？
我对接三方对接得多，对OAuth2比较熟悉，可以使用OAuth2和JWT来搭建单点服务端

**Comment by zch1477610884** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xkcoding/spring-boot-demo"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月27日(星期四) 下午4:35
收件人:&nbsp;"xkcoding/spring-boot-demo"<spring-boot-demo@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [xkcoding/spring-boot-demo] 老哥，可以整一个SSO的项目 (#12)





 
我可以写sso提交pr不？
 我对接三方对接得多，对OAuth2比较熟悉，可以使用OAuth2和JWT来搭建单点服务端

**Comment by sandubuhan** [comment]
哈哈昂

**Comment by xkcoding** [comment]
> 我可以写sso提交pr不？ 我对接三方对接得多，对OAuth2比较熟悉，可以使用OAuth2和JWT来搭建单点服务端

可以，如果可以提交，十分感谢

**Comment by 07SD** [comment]
creative mode

**Comment by 07SD** [comment]
Resolve please
