### ISSUE TITLE
关于spring security 的一些疑问

### ISSUE THREAD

**Issue by changdy** [xkcoding/spring-boot-demo#129]
看了下菊苣的Security 模块 , 感觉相当于把整个认证功能重写了,那其实和自己利用Spring 的拦截器实现差不多了 .感觉反而使用Security 有些多余 . 并且有些定制化的需求又是无法避免的 ,这又导致重写是必须的 , 看了好多Security模板 , 我也是觉得 你的是最贴切实际业务的.
那是不是说明 ,关于认证和授权这一块并不一定需要引入一个单独的依赖 , 自己如果能实现需求也可以.
菊苣有什么看法?

**Comment by QuantumSuperPositionCat** [comment]
而且jwt的特性也没用完全利用，每个请求都要查数据库，性能拉跨。

**Comment by xkcoding** [comment]
> 看了下菊苣的Security 模块 , 感觉相当于把整个认证功能重写了,那其实和自己利用Spring 的拦截器实现差不多了 .感觉反而使用Security 有些多余 . 并且有些定制化的需求又是无法避免的 ,这又导致重写是必须的 , 看了好多Security模板 , 我也是觉得 你的是最贴切实际业务的.
> 那是不是说明 ,关于认证和授权这一块并不一定需要引入一个单独的依赖 , 自己如果能实现需求也可以.
> 菊苣有什么看法?

是的，其实没必要，有些东西在很多场景，单纯就是为了技术而用技术。。。。:cry:
