### ISSUE TITLE
[FEATURE] 整合 u2report 完成网页报表设计功能

### ISSUE THREAD

**Issue by lltx** [xkcoding/spring-boot-demo#158]
### 你在什么场景下需要该功能？

UReport2 是一款基于架构在 Spring 之上纯 Java 的高性能报表引擎，通过迭代单元格可以实现任意复杂的中国式报表。 在 UReport2 中，提供了全新的基于网页的报表设计器，可以在 Chrome、Firefox、Edge 等各种主流浏览器运行（IE 浏览器除外）。使用 UReport2，打开浏览器即可完成各种复杂报表的设计制作

[https://www.w3cschool.cn/ureport](https://www.w3cschool.cn/ureport)

### 描述可能的解决方案

通过整合  ureport-spring-boot-starter 非常方便完成 单机、集群的整合

### 描述你认为的候选方案

由于官方未提供 spring boot 兼容 和 JAVA编程式注入，使用xml 形式配置不太适合 spring boot 

### 其他信息
依赖如下 jar 
关于 [oss-spring-boot-starter ](https://github.com/pig-mesh/oss-spring-boot-starter)使用可参考，兼容所有 S3 协议的分布式文件存储系统
关于 [ureport-spring-boot-starter ](https://github.com/pig-mesh/ureport-spring-boot-starter)使用可参考，UReport2 的 spring boot 封装

**Comment by xkcoding** [comment]
感谢冷神~

因本人操作失误，PR 未被合并。。sorry
