### ISSUE TITLE
[BUG] thymeleaf集成 报错：Error resolving template [page/login], template might not exist or might not be accessible by any of the configured Template Resolvers

### ISSUE THREAD

**Issue by peade** [xkcoding/spring-boot-demo#162]
**请先看[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md?utm_source=hacpai.com)**，并尝试到 **[issue 列表](https://github.com/xkcoding/spring-boot-demo/issues)** 搜寻是否已经有人遇到过同样的问题。

----

### 描述问题
练习集成thymeleaf的demo项目，到跳转“page/login”时，一直报错：

```bash
Error resolving template [page/index], template might not exist or might not be accessible by any of the configured Template Resolvers
```
我参考错误处理的练习demo中的error.html页面，把head中`th:replace="~{common/head :: header}`去掉，就能正常运行了。
### 期待的结果
不知道是我哪块配置的问题，导致了这个`th:replace`不起作用。
我看了下配置，和demo里的没有什么差别。不知道是不是要做什么特殊配置？

**Comment by xkcoding** [comment]
请问你是直接跑的我的 demo 么？我这边运行没有复现你说的这个问题。。。

**Comment by peade** [comment]
> 请问你是直接跑的我的 demo 么？我这边运行没有复现你说的这个问题。。。

我有点忘记当时是怎么弄的了。 我可能不是直接运行你的那个demo，是自己照着抄练习的。
可能是我之前哪个地方没抄对吧。

这块我已经学习过去了。

感谢你的回复
