### ISSUE TITLE
项目能运行，但是idea里好多地方飘红，这个是怎么解决

### ISSUE THREAD

**Issue by Shankiss** [xkcoding/spring-boot-demo#164]
![image](https://user-images.githubusercontent.com/24237709/98095263-4df19280-1ec5-11eb-9568-e620457b5670.png)
![image](https://user-images.githubusercontent.com/24237709/98095295-577afa80-1ec5-11eb-88a1-31ba66c79841.png)

**Comment by xkcoding** [comment]
请安装 idea 的 `lombok` 插件~
