### ISSUE TITLE
希望可以有一个 scheduled 的 demo: spring-boot-demo-scheduled

### ISSUE THREAD

**Issue by lq920320** [xkcoding/spring-boot-demo#17]

**Comment by xkcoding** [comment]
模块名|介绍
-- | --
spring-boot-demo-task | spring-boot 快速实现定时任务
spring-boot-demo-task-quartz | spring-boot 整合 quartz，并实现对定时任务的管理，包括新增定时任务，删除定时任务，暂停定时任务，恢复定时任务，修改定时任务启动时间，以及定时任务列表查询，提供前端页面
spring-boot-demo-task-xxl-job | spring-boot 整合xxl-job，并提供绕过 xxl-job-admin 对定时任务的管理的方法，包括定时任务列表，触发器列表，新增定时任务，删除定时任务，停止定时任务，启动定时任务，修改定时任务，手动触发定时任务

请问这三个demo不满足需求嘛~

**Comment by xkcoding** [comment]
@lq920320

**Comment by lq920320** [comment]
> 
> 模块名 	介绍
> spring-boot-demo-task 	spring-boot 快速实现定时任务
> spring-boot-demo-task-quartz 	spring-boot 整合 quartz，并实现对定时任务的管理，包括新增定时任务，删除定时任务，暂停定时任务，恢复定时任务，修改定时任务启动时间，以及定时任务列表查询，提供前端页面
> spring-boot-demo-task-xxl-job 	spring-boot 整合xxl-job，并提供绕过 xxl-job-admin 对定时任务的管理的方法，包括定时任务列表，触发器列表，新增定时任务，删除定时任务，停止定时任务，启动定时任务，修改定时任务，手动触发定时任务
> 
> 请问这三个demo不满足需求嘛~


可以的，不好意思，先入为主地考虑了命名，spring-boot-demo-task 可以满足，直接去找'schedule' 了。

**Comment by xkcoding** [comment]
哈哈，没事没事，学习愉快~
