### ISSUE TITLE
demo-orm-jdbctemplate 运行失败[BUG]

### ISSUE THREAD

**Issue by ywltxz** [xkcoding/spring-boot-demo#198]
![image](https://user-images.githubusercontent.com/43531447/113126955-c7aa6400-924a-11eb-82cf-fd15bdc635a9.png)

**Comment by icyfang** [comment]
报错信息不挺清楚的，没有 spring-boot-demo 这个库

**Comment by xkcoding** [comment]
README 中有提到：
> 注意：每个 demo 均有详细的 README 配套，使用 demo 前记得先看看哦~
> 注意：运行各个 demo 之前，有些是需要事先初始化数据库数据的，亲们别忘记了哦~

关于 `jdbctemplate` 这个 demo，您需要先创建 `spring-boot-demo` 数据库，然后程序会自动创建表结构和初始化一些测试数据。
