### ISSUE TITLE
关于把Pom.xml放到根目录

### ISSUE THREAD

**Issue by wotemenige** [xkcoding/spring-boot-demo#201]
Maven Projects 找不到的童鞋，可以勾上 IDEA 顶部工具栏的 View -> Tool Buttons ，然后 Maven Projects 的面板就会出现在 IDEA 的右侧

找不到 Tool Buttons啊

**Comment by xkcoding** [comment]
新版本的 idea 是这个路径
`View --> Appearance -->  Tool Window Bars`

**Comment by wotemenige** [comment]
好的





------------------ 原始邮件 ------------------
发件人: Yangkai.Shen ***@***.***&gt;
发送时间: 2021年4月14日 18:11
收件人: xkcoding/spring-boot-demo ***@***.***&gt;
抄送: Hock ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[xkcoding/spring-boot-demo] 关于把Pom.xml放到根目录 (#201)





 
新版本的 idea 是这个路径
 View --&gt; Appearance --&gt;  Tool Window Bars

**Comment by wotemenige** [comment]
> 新版本的 idea 是这个路径
> `View --> Appearance --> Tool Window Bars`

找到了，顺便再问一下；他在右边了。有啥用啊??? 新人不大明白
