### ISSUE TITLE
提问： 有考虑加入ldap吗？

### ISSUE THREAD

**Issue by fxbin** [xkcoding/spring-boot-demo#23]

**Comment by xkcoding** [comment]
ldap这个之前考虑过，但是由于我目前接触的较少，所以开发的时候就没考虑了，现在如果你需要的话，我可以考虑在TODO里加入 :smile:

**Comment by fxbin** [comment]
> ldap这个之前考虑过，但是由于我目前接触的较少，所以开发的时候就没考虑了，现在如果你需要的话，我可以考虑在TODO里加入 😄

我最近实现了一版，但是特别简陋，想学习下更优秀的实现方式

**Comment by xkcoding** [comment]
> > ldap这个之前考虑过，但是由于我目前接触的较少，所以开发的时候就没考虑了，现在如果你需要的话，我可以考虑在TODO里加入 😄
> 
> 我最近实现了一版，但是特别简陋，想学习下更优秀的实现方式

可以提个PR啊，正好可以交流学习下

**Comment by fxbin** [comment]
> > > ldap这个之前考虑过，但是由于我目前接触的较少，所以开发的时候就没考虑了，现在如果你需要的话，我可以考虑在TODO里加入 😄
> > 
> > 
> > 我最近实现了一版，但是特别简陋，想学习下更优秀的实现方式
> 
> 可以提个PR啊，正好可以交流学习下

可以的，一起学习😄

**Comment by fxbin** [comment]
> > > ldap这个之前考虑过，但是由于我目前接触的较少，所以开发的时候就没考虑了，现在如果你需要的话，我可以考虑在TODO里加入 😄
> > 
> > 
> > 我最近实现了一版，但是特别简陋，想学习下更优秀的实现方式
> 
> 可以提个PR啊，正好可以交流学习下

已提交RP

**Comment by xkcoding** [comment]
十分感谢！ #34
