### ISSUE TITLE
你好，我觉得可以加入Shiro和Security

### ISSUE THREAD

**Issue by qq742464260** [xkcoding/spring-boot-demo#25]
现在登录验证，权限控制这里两个用的蛮多的，希望加下

**Comment by xkcoding** [comment]
shiro 正在完善，**`目前尚未完成`**，模块名：spring-boot-demo-rbac-shiro

security 已经实现，模块名：spring-boot-demo-rbac-security

**Comment by qq742464260** [comment]
> shiro 正在完善，**`目前尚未完成`**，模块名：spring-boot-demo-rbac-shiro
> 
> security 已经实现，模块名：spring-boot-demo-rbac-security

好的，谢谢
