### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by hacker402** [xkcoding/spring-boot-demo#27]
发现个错别字
![image](https://user-images.githubusercontent.com/23608747/63477816-9a67d280-c4b9-11e9-9575-a1e478e67c5e.png)

**Comment by meetshawn** [comment]
哈哈，不要这么实诚嘛，哈哈


 
---原始邮件---
发件人: "Mr.W"<notifications@github.com>
发送时间: 2019年8月22日 08:49:15
收件人: "xkcoding/spring-boot-demo"<spring-boot-demo@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [xkcoding/spring-boot-demo] 错别字 (#27)



发现个错别字

**Comment by xkcoding** [comment]
- -||  我故意写成 `食用` 的 :joy:
