### ISSUE TITLE
[BUG] zookeeper 在install项目的时候报错

### ISSUE THREAD

**Issue by fpx77777** [xkcoding/spring-boot-demo#272]
**请先看[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md?utm_source=hacpai.com)**，并尝试到 **[issue 列表](https://github.com/xkcoding/spring-boot-demo/issues)** 搜寻是否已经有人遇到过同样的问题。

----

### 描述问题
![Uploading image.png…]()

Unable to make field private com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors com.sun.tools.javac.processing.JavacProcessingEnvironment.discoveredProcs accessible: module jdk.compiler does not "opens com.sun.tools.javac.processing" to unnamed module @3976ebfa

```bash
日志内容
```

### 期待的结果

希望能够运行zookeeper，学习其内容

### 截屏或录像

见上图

### 其他信息

无

**Comment by guxiren** [comment]
您的邮件已收到！

**Comment by fpx77777** [comment]
![Uploading Snipaste_2024-06-20_13-39-46.png…]()

**Comment by fpx77777** [comment]
https://blog.csdn.net/weixin_43975684/article/details/120729125

java版本太高导致的问题，已解决。谢谢。
