### ISSUE TITLE
老哥，有考虑出一套gradle版本的吗？

### ISSUE THREAD

**Issue by Howeloveyou** [xkcoding/spring-boot-demo#29]
最近刚好在学习使用gradle，建议可以出maven和gradle双版本

**Comment by xkcoding** [comment]
gradle 用的不是很熟练，待我去学习一番:flushed:

**Comment by xkcoding** [comment]
看了下gradle的用法，也尝试了下，因为目前demo个数比较多，所以暂时不考虑双版本啦，精力不够，十分抱歉
