### ISSUE TITLE
spring-boot-demo-actuator 输入用户密码后跳到错误页面

### ISSUE THREAD

**Issue by W-quan** [xkcoding/spring-boot-demo#3]

**Comment by xkcoding** [comment]
你好，是不是访问的路径不正确呢？
例如：
1. 打开浏览器，访问：http://localhost:8090/sys/actuator/mappings ，输入用户名(xkcoding)密码(123456)即可看到所有的mapping信息
2. 访问：http://localhost:8090/sys/actuator/beans ，输入用户名(xkcoding)密码(123456)即可看到所有 Spring 管理的Bean

另外，README.md 已经更新，可以参考：https://github.com/xkcoding/spring-boot-demo/blob/master/spring-boot-demo-actuator/README.md#%E7%AB%AF%E7%82%B9%E6%9A%B4%E9%9C%B2%E5%9C%B0%E5%9D%80
