### ISSUE TITLE
邮件发送demo

### ISSUE THREAD

**Issue by tiangongerhao** [xkcoding/spring-boot-demo#36]
我将邮箱配置换成自己的163邮箱之后为什么发送出去之后会变成垃圾邮件发送给对方？
前两天测试demo上的邮箱可以正常发送，现在demo上的邮箱不能使用了。
多谢！

**Comment by xkcoding** [comment]
1. 如果变成垃圾邮件的话，这个应该是对方的收件策略吧
2. 前两天可以用，现在不能用，是邮箱不能使用了吗？

**Comment by xkcoding** [comment]
已测试，确实不能使用了，因为之前使用的是 hutool 作者提供的邮箱，估计是密码已经被修改了，换成自己的邮箱应该。

**Comment by tiangongerhao** [comment]
我这边用的是163邮箱进行的发送，用两个QQ邮箱接收测试，一个已经能够正常接收，另外一个就直接进入了垃圾箱中。不晓得是为什么。

**Comment by tiangongerhao** [comment]
不好意思，应该是两个邮箱都不可以，可以的那个下午的时候我设置了一个“这不是垃圾邮件”。

**Comment by xkcoding** [comment]
已经更换邮箱地址，测试可用，后期如果不能用，请再通知一下，谢谢！
