### ISSUE TITLE
提问：是否考虑 springboot 集成elasticsearch 7.X 使用rest-high-level-client

### ISSUE THREAD

**Issue by fxbin** [xkcoding/spring-boot-demo#38]
是否考虑 springboot 集成elasticsearch 7.X 使用rest-high-level-client

**Comment by xkcoding** [comment]
elasticsearch 都已经 7.x 了？！
这也升级的太快了吧，这个我抽空会额外添加一个 demo 的，感谢反馈~

**Comment by fxbin** [comment]
> elasticsearch 都已经 7.x 了？！
> 这也升级的太快了吧，这个我抽空会额外添加一个 demo 的，感谢反馈~

OK， 可以提pull request 吧，最近正好在做这个

**Comment by xkcoding** [comment]
可以的，欢迎贡献

**Comment by chennaibing** [comment]
spring-boot-starter-data-elasticsearch 才支持到6.8版本，7.x的支持有计划表吗

**Comment by xkcoding** [comment]
> spring-boot-starter-data-elasticsearch 才支持到6.8版本，7.x的支持有计划表吗

你是建议我在现有的 `spring-boot-demo-elasticsearch`  模块上修改呢，还是新增一个 7.x 的demo 呢？？

**Comment by xkcoding** [comment]
@chennaibing 7.x版本的demo已经上新了，感谢 @fxbin 的 PR #51
