### ISSUE TITLE
[QUESTION]你好 我想问一下rbac-security项目下的权限表 权限表达式字段是干嘛用的

### ISSUE THREAD

**Issue by RobertoHuang** [xkcoding/spring-boot-demo#39]
你好 我想问一下rbac项目下的权限表 权限表达式字段是干嘛用的

是给前端做什么处理的吗？不太懂前端所以麻烦告知一下 谢谢

**Comment by xkcoding** [comment]
前端通过权限表达式，对按钮或者菜单进行显示/隐藏操作
后端通过权限表达式，对接口做拦截鉴权操作
