### ISSUE TITLE
[BUG] spring session集成时需要 Redis 的密码

### ISSUE THREAD

**Issue by 124905985** [xkcoding/spring-boot-demo#41]
### 描述问题

spring session集成时需要Redis的密码

### 期待的结果

无

### 截屏或录像

无

### 其他信息

无

**Comment by 124905985** [comment]
描述缺陷：Redis缺链接密码

**Comment by xkcoding** [comment]
需不需要密码是根据你自己的 redis 环境来的

我demo的测试环境默认是不加密码的，生产环境需要添加
