### ISSUE TITLE
可以整合个jfinal的ActiveRecord，对db操作挺舒服。

### ISSUE THREAD

**Issue by YangShengQuan** [xkcoding/spring-boot-demo#42]

**Comment by xkcoding** [comment]
那就加个 `spring-boot-demo-orm-jfinal`

**Comment by YangShengQuan** [comment]
> 那就加个 `spring-boot-demo-orm-jfinal`

之前自己整合过，感觉返回json的时候怪怪的。可能没到位，得继续加油。哈哈

**Comment by xkcoding** [comment]
> > 那就加个 `spring-boot-demo-orm-jfinal`
> 
> 之前自己整合过，感觉返回json的时候怪怪的。可能没到位，得继续加油。哈哈

欢迎 PR

**Comment by pigxcloud** [comment]
直接用 mybatis-plus 支持 model ActiveRecord

**Comment by xkcoding** [comment]
@pigxcloud 我和冷神想到一块儿去了，@YangShenQuan 你可以看看我在 `spring-boot-demo-orm-mybatis-plus` 模块里新增的 `ActiveRecord` 的代码示例，[直达地址](https://github.com/xkcoding/spring-boot-demo/blob/master/spring-boot-demo-orm-mybatis-plus/src/test/java/com/xkcoding/orm/mybatis/plus/activerecord/ActiveRecordTest.java)。

关于 jfinal 的，后续有空的时候，再考虑添加~

**Comment by YangShengQuan** [comment]
> @pigxcloud 我和冷神想到一块儿去了，@YangShenquan 你可以看看我在 `spring-boot-demo-orm-mybatis-plus` 模块里新增的 `ActiveRecord` 的代码示例，[直达地址](https://github.com/xkcoding/spring-boot-demo/blob/master/spring-boot-demo-orm-mybatis-plus/src/test/java/com/xkcoding/orm/mybatis/plus/activerecord/ActiveRecordTest.java)。
> 
> 关于 jfinal 的，后续有空的时候，再考虑添加~

好久都没有用mybatis，刚刚看到你和冷神的想法，正好可以去学习一波。哈哈

**Comment by xkcoding** [comment]
那我这个issue，暂时先关闭啦。后续如果有机会集成 JFinal 的 ActiveRecord ，我会在 Issue 里通知 :smile:
