### ISSUE TITLE
[BUG]dubbo的demo里面consumer的测试用例是不是有问题？

### ISSUE THREAD

**Issue by wanghui5257** [xkcoding/spring-boot-demo#46]
### 描述问题

dubbo的demo里面consumer的测试用例 maven打包校验不通过，注释可以打包完成

```bash
日志内容
```

### 期待的结果

maven打包测试校验通过

### 截屏图片
![image](https://user-images.githubusercontent.com/1677849/64521361-71a16300-d32a-11e9-9402-880c1212adeb.png)

**Comment by xkcoding** [comment]
你尝试在根目录执行下 `mvn clean -DskipTests=true package` 呢
