### ISSUE TITLE
[老哥,何时加个网关模块]

### ISSUE THREAD

**Issue by lichen5201314** [xkcoding/spring-boot-demo#47]

**Comment by xkcoding** [comment]
加个网关模块，是啥意思呀，gateway或者zuul引入就可以玩了诶。。。不需要demo吧~

**Comment by lichen5201314** [comment]
> 加个网关模块，是啥意思呀，网关或者zuul引入就可以玩了诶......不需要演示吧〜
网关里还是有很多filter的,

**Comment by lichen5201314** [comment]
zuul  里还是有很多filter不知道怎么用的 -- \
