### ISSUE TITLE
spring-boot 集成 Zookeeper 结合AOP实现分布式锁[BUG]

### ISSUE THREAD

**Issue by 3Flos** [xkcoding/spring-boot-demo#52]
### 描述问题
![image](https://user-images.githubusercontent.com/23204861/65026638-88b80480-d96b-11e9-871b-167495bba235.png)

### 期待的结果
正确执行

### 截屏或录像
![image](https://user-images.githubusercontent.com/23204861/65026638-88b80480-d96b-11e9-871b-167495bba235.png)
改成以下方式就没问题
![image](https://user-images.githubusercontent.com/23204861/65026728-b69d4900-d96b-11e9-8e6e-bedfa86f494d.png)

**Comment by xkcoding** [comment]
存在异常日志嘛

**Comment by 3Flos** [comment]
> 存在异常日志嘛
第一个问题可能是判断错误会直接continue;
第二个问题可能需要传入具体对象获取对应字段值，而不是传入class

**Comment by xkcoding** [comment]
十分感谢！
