### ISSUE TITLE
Spring-boot-demo中的基于Guava实现的限流，多方法注解不能限流

### ISSUE THREAD

**Issue by Git950715** [xkcoding/spring-boot-demo#55]
### 描述问题
Spring-boot-demo中的spring-boot-demo-ratelimit-guava项目，我如果把注解RateLimiter注解到不同的方法上面，就不能对不同的方法实现不同令牌的限流。

### 期待的结果
在不使用Redis的情况下，能不能就通过Guava的RateLimiter方法实现单服务不同方法的不同令牌的限流。

**Comment by xkcoding** [comment]
我这边测试是可以的请问您是怎么测试的呢？？

![image](https://user-images.githubusercontent.com/10429917/65291345-8b8e4180-db85-11e9-8f5f-1a631997e6c2.png)

**Comment by Git950715** [comment]
我是进行多方法并发测试的，如果单方法并发测试是肯定可以的，但是多方法并发测试就会显露出问题了。

**Comment by Git950715** [comment]
`private static final ConcurrentMap<String, RateLimiter> rateLimiterMap = new ConcurrentHashMap<String, RateLimiter>();
	
    private Logger log = LoggerFactory.getLogger(RateLimiterAspect.class);
    
    /***
     * 定义切入点拦截规则，拦截OperationLog注解的方法
     */
    @Pointcut("@annotation(com.poyi.annotation.RateLimit)")
    public void rateLimit() {
    }
    
    @Around("rateLimit()")
    public Object recordLog(ProceedingJoinPoint joinPoint) throws Throwable {
    	MethodSignature signature = (MethodSignature) joinPoint.getSignature();
        Method method = signature.getMethod();
        // 通过 AnnotationUtils.findAnnotation 获取 RateLimiter 注解
        RateLimit rateLimiter = AnnotationUtils.findAnnotation(method, RateLimit.class);
        if (rateLimiter != null && rateLimiter.qps() > RateLimit.NOT_LIMITED) {
            double qps = rateLimiter.qps();
            // 重新设置 QPS
            if (rateLimiterMap.get(method.getName()) == null) {
                rateLimiterMap.put(method.getName(), RateLimiter.create(qps));
            }
            log.info("【{}】限流数:{}", method.getName(),rateLimiterMap.get(method.getName()).getRate());
            // 尝试获取令牌
            if (rateLimiterMap.get(method.getName())!=null && !rateLimiterMap.get(method.getName()).tryAcquire(rateLimiter.timeout(), rateLimiter.timeUnit())) {
            	log.info("【{}】进入限流", method.getName());
                throw new ServiceException("手速太快了，慢点儿吧~");
            }else{
            	log.info("【{}】没有进入限流", method.getName());
            }
        }
        return joinPoint.proceed();
    }`

**Comment by xkcoding** [comment]
十分感谢！
