### ISSUE TITLE
[BUG]利用Spring缓存注解如@Cacheable操作redis，后台查看redis中的数据，value是乱码

### ISSUE THREAD

**Issue by RhymeXY** [xkcoding/spring-boot-demo#57]
### 描述问题

xk，你好；
在 `spring-boot-demo-cache-redis` 项目中，利用Spring缓存注解如 `@Cacheable` 操作redis，后台查看redis中的数据，key没有乱码，但是value是乱码；
利用 `RedisTemplate` 操作value没有乱码。

### 期待的结果

期望利用Spring缓存注解如@Cacheable操作redis，查看redis中的数据，value不是乱码。

### 截屏或录像

![image](https://user-images.githubusercontent.com/30640716/66048114-9371bc80-e55b-11e9-8b96-f338bba82927.png)

**Comment by meetshawn** [comment]
我只是有遇到过，序列化的问题，程序取没有问题，但是给其他程序用也是乱码，自己加个序列化就可以了

**Comment by xkcoding** [comment]
@RhymeXY 这个默认是以序列化的形式存入 `Redis` 的，如果你想要去 `Redis` 检查数据的话，可以参考我新提交的代码，将数据序列化为 `json` 格式，但是需要注意的是，生产环境不要随意切换序列化的方式哦，会因为序列化方式不一致，导致反序列化失败的情况。

https://github.com/xkcoding/spring-boot-demo/blob/ddb3c50e1d2fa8f523d962d2a9b699089bf348b4/spring-boot-demo-cache-redis/src/main/java/com/xkcoding/cache/redis/config/RedisConfig.java#L50-L60
