### ISSUE TITLE
多模块问题

### ISSUE THREAD

**Issue by kitonGao** [xkcoding/spring-boot-demo#60]
请问一下在spring-boot-dubbo中是如何创建子模块下的子模块，我本地一创建，就会报错。只能穿件一层子模块

**Comment by xkcoding** [comment]
观察 `spring-boot-demo-dubbo` 子模块下的 `pom` 文件中的`package` 节点，设置为 pom 就行了，同时把 子模块的子模块放在 modules 里，和普通多模块一样的呀

**Comment by kitonGao** [comment]
嗯，懂了。 IDEA默认的配置文件不自动改变，建立3层模块后还是原来的父模块。导致错了。

在 2019-10-09 22:08:57，"Yangkai.Shen" <notifications@github.com> 写道：


观察 spring-boot-demo-dubbo 子模块下的 pom 文件中的package 节点，设置为 pom 就行了，同时把 子模块的子模块放在 modules 里，和普通多模块一样的呀
