### ISSUE TITLE
老哥我是新手。下载下来的项目怎么不会运行呀，都是灰色的，是不是什么依赖没下载全？

### ISSUE THREAD

**Issue by aLLLiyyy** [xkcoding/spring-boot-demo#61]
![QQ截图20191013002020](https://user-images.githubusercontent.com/36837316/66704550-7d2fe180-ed4f-11e9-8b55-707a0ed740e8.png)
![Uploading QQ截图20191013002020.png…]()

**Comment by xkcoding** [comment]
maven 依赖下不下来吗？

**Comment by zihang5127** [comment]
右键pom.xml  应该有个maven add什么的， 你这个还不是maven项目。

**Comment by zj-dreamly** [comment]
如果你IDEA装过maven的话，右边导航点maven，点加号，找到pom.xml，ok就行了

**Comment by aLLLiyyy** [comment]
![Uploading 0000.png…]()
![Uploading 1111111111111.png…]()

怎么一堆这样的问题是怎么回事呀

**Comment by aLLLiyyy** [comment]
不行呀，提示Unable to import maven project: See logs for details，看下日志有一大堆，也不知道哪里问题。
1) No implementation for org.apache.maven.model.path.PathTranslator was bound.
  while locating org.apache.maven.model.path.PathTranslator
    for field at org.apache.maven.model.interpolation.AbstractStringBasedModelInterpolator.pathTranslator(Unknown Source)
  at org.codehaus.plexus.DefaultPlexusContainer$1.configure(DefaultPlexusContainer.java:350)

2) No implementation for org.apache.maven.model.path.UrlNormalizer was bound.
  while locating org.apache.maven.model.path.UrlNormalizer
    for field at org.apache.maven.model.interpolation.AbstractStringBasedModelInterpolator.urlNormalizer(Unknown Source)
  at org.codehaus.plexus.DefaultPlexusContainer$1.configure(DefaultPlexusContainer.java:350)

2 errors 
java.lang.RuntimeException: com.google.inject.CreationException: Unable to create injector, see the following errors:

**Comment by aLLLiyyy** [comment]
> 如果你IDEA装过maven的话，右边导航点maven，点加号，找到pom.xml，ok就行了

你有联系方式没帮我看看怎么回事
