### ISSUE TITLE
[FEATURE] 作者能否在demo里尽量加一些controller展示用法

### ISSUE THREAD

**Issue by cs8** [xkcoding/spring-boot-demo#65]
首先感谢作者的辛勤付出，写出这么多的demo。我的意见是:对于新手来说，有的demo里面只是集成了个功能模块，但是似乎并没有展示怎么简单的使用，比如mybatis，我觉得如果demo里加一个controller 来展示一下如何使用会更好。

**Comment by xkcoding** [comment]
emmm.....像那些数据操作的，我这边一般都是已单元测试存在的，您可以找下，在 `test` 包下
