### ISSUE TITLE
spring-boot-demo-logback控制台输出彩色日志

### ISSUE THREAD

**Issue by malagebi** [xkcoding/spring-boot-demo#66]
### 你在什么场景下需要该功能？

个人习惯 喜欢控制台 输出彩色日志。

### 描述可能的解决方案

请尽量清晰精准地描述你期待我们要做的，描述你想到的实现方案。

### 描述你认为的候选方案

请尽量清晰精准地描述你能接受的候选解决方案。

### 其他信息

请提供关于该功能建议的其他附加信息。

**Comment by xkcoding** [comment]
OK，这个好实现，马上安排 - - :smile:

**Comment by malagebi** [comment]
> OK，这个好实现，马上安排 - - 😄

安排

**Comment by malagebi** [comment]
跟  springboot   默认控制台输出一样， 彩色 而已  不换行

**Comment by xkcoding** [comment]
已经安排上了，更新 `logback` 模块即可 ，具体可以修改可以查看本次提交记录 https://github.com/xkcoding/spring-boot-demo/commit/819b912639006801b80492f6e143a7785cd78c96
