### ISSUE TITLE
可以做一个整合FTP的demo吗

### ISSUE THREAD

**Issue by XCX-OOO** [xkcoding/spring-boot-demo#69]
如题

**Comment by xkcoding** [comment]
FTP 这个就是普通工具类就可以啦，不需要集成吧 :joy:

**Comment by XCX-OOO** [comment]
我主要是想找找看有没有不一样的思路和方法

**Comment by xkcoding** [comment]
sorry 哈，这个我这边应该也是去找个工具类去做啦，就不集成了，推荐个 [hutool](https://github.com/looly/hutool)

**Comment by XCX-OOO** [comment]
好的,谢谢
