### ISSUE TITLE
mvn 编译测试失败

### ISSUE THREAD

**Issue by gitplyx** [xkcoding/spring-boot-demo#7]
提示数据库连接失败，请问数据库的连接信息在哪里配置的

**Comment by xkcoding** [comment]
在每个module对应的 application.yml 文件里

**Comment by gitplyx** [comment]
但是我并没有看到相关的数据库的配置在里面

 

发件人: noreply@github.com [mailto:noreply@github.com] 代表 Yangkai.Shen
发送时间: 2019年5月20日 9:30
收件人: xkcoding/spring-boot-demo
抄送: Mikel Pan; Author
主题: Re: [xkcoding/spring-boot-demo] mvn 编译测试失败 (#7)

 

在每个module对应的 application.yml 文件里

**Comment by xkcoding** [comment]
可以把错误日志贴一下吗，我帮你看看
