### ISSUE TITLE
ServerTask方法下面的定时任务不能自动执行，需要增加 @EnableScheduling[BUG]

### ISSUE THREAD

**Issue by yihangxu** [xkcoding/spring-boot-demo#70]
**请先看[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md?utm_source=hacpai.com)**，并尝试到 **[issue 列表](https://github.com/xkcoding/spring-boot-demo/issues)** 搜寻是否已经有人遇到过同样的问题。

----

### 描述问题

请尽量清晰精准地描述你碰到的问题。

```bash
日志内容
```

### 期待的结果

请尽量清晰精准地描述你所期待的结果。

### 截屏或录像

如果可能，请尽量附加截图或录像来描述你遇到的问题。

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by yihangxu** [comment]
websocket 包下的ServerTask 类的定时任务在spring boot 2.0.0版本需要增加@EnableScheduling 注解

**Comment by xkcoding** [comment]
@yihangxu  你可以看看 `SpringBootDemoWebsocketApplication.java` 这个类哦，我是加在启动类上面的~
https://github.com/xkcoding/spring-boot-demo/blob/0378ad012f2b1cbcd23f21de83e9c829f07539d1/spring-boot-demo-websocket/src/main/java/com/xkcoding/websocket/SpringBootDemoWebsocketApplication.java#L21
