### ISSUE TITLE
hutool依赖包无法下载

### ISSUE THREAD

**Issue by AresJfeng** [xkcoding/spring-boot-demo#87]
<dependency>
	<groupId>cn.hutool</groupId>
	<artifactId>hutool-all</artifactId>
</dependency>
这个依赖下载不下来.
另外,为什么要用这个工具包呢?有什么优点吗?

**Comment by xkcoding** [comment]
这个依赖不应该下不下来诶，hutool 是个优秀的国产 Java 工具包，您可以去看看 https://github.com/looly/hutool
