### ISSUE TITLE
[BUG]spring-boot-demo-websocket-socketio 模块中，index.html日期格式化

### ISSUE THREAD

**Issue by alexanders9** [xkcoding/spring-boot-demo#96]
### 描述问题
moment().format('YYYY-MM-dd HH:mm:ss.SSS') 应该是 moment().format('YYYY-MM-DD HH:mm:ss.SSS')

### moment 官网截图
![image](https://user-images.githubusercontent.com/44674354/72662349-ff9c0180-3a20-11ea-9c78-dabf70ee99d5.png)
> [monment格式化日期](http://momentjs.cn/docs/#/parsing/)

**Comment by xkcoding** [comment]
感谢，已修复！
